export const SCHOOLS = [
  { id: 1, name: 'Collège Saint-Michel', city: 'Cotonou', validated: true },
  { id: 2, name: 'Lycée Mathieu Bouké', city: 'Cotonou', validated: true },
  { id: 3, name: 'Groupe Scolaire Les Hirondelles', city: 'Abomey-Calavi', validated: true },
  { id: 4, name: 'École Primaire Sainte-Cécile', city: 'Porto-Novo', validated: false },
  { id: 5, name: 'Lycée Technique Coulibaly', city: 'Parakou', validated: true },
]

export const CLASSES = [
  { id: 'cp', label: 'CP' },
  { id: 'ce1', label: 'CE1' },
  { id: 'ce2', label: 'CE2' },
  { id: 'cm1', label: 'CM1' },
  { id: 'cm2', label: 'CM2' },
  { id: '6e', label: '6ème' },
  { id: '5e', label: '5ème' },
  { id: '4e', label: '4ème' },
  { id: '3e', label: '3ème' },
  { id: '2nd', label: '2nde' },
  { id: '1ere', label: '1ère' },
  { id: 'tle', label: 'Tle' },
]

export const SUPPLIES = [
  {
    id: 1,
    name: 'Cahier grand format 200 pages',
    emoji: '📓',
    required: true,
    category: 'obligatoire',
    priceStd: 500,
    pricePrem: 800,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80',
    description: 'Cahier grands carreaux, couverture rigide',
    badge: null,
  },
  {
    id: 2,
    name: 'Stylo bille bleu BIC',
    emoji: '🖊️',
    required: true,
    category: 'obligatoire',
    priceStd: 150,
    pricePrem: 350,
    image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400&q=80',
    description: 'Stylo bille écriture fluide',
    badge: null,
  },
  {
    id: 3,
    name: 'Règle 30cm',
    emoji: '📏',
    required: true,
    category: 'obligatoire',
    priceStd: 200,
    pricePrem: 450,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&q=80',
    description: 'Règle graduée transparente',
    badge: null,
  },
  {
    id: 4,
    name: 'Compas scolaire',
    emoji: '🔵',
    required: false,
    category: 'optionnel',
    priceStd: 500,
    pricePrem: 1200,
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&q=80',
    description: 'Compas métal avec porte-mine',
    badge: null,
  },
  {
    id: 5,
    name: 'Trousse',
    emoji: '🎒',
    required: false,
    category: 'optionnel',
    priceStd: 800,
    pricePrem: 2000,
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=400&q=80',
    description: 'Trousse double compartiment',
    badge: null,
  },
  {
    id: 6,
    name: 'Calculatrice scientifique',
    emoji: '🔢',
    required: true,
    category: 'obligatoire',
    priceStd: 3500,
    pricePrem: 7000,
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&q=80',
    description: 'Calculatrice Casio fx-82',
    badge: 'Sous-titré',
  },
  {
    id: 7,
    name: 'Couvre-cahiers x10',
    emoji: '📚',
    required: false,
    category: 'optionnel',
    priceStd: 500,
    pricePrem: 900,
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&q=80',
    description: 'Plastique transparent, lot de 10',
    badge: null,
  },
  {
    id: 8,
    name: 'Taille-crayon',
    emoji: '✏️',
    required: false,
    category: 'optionnel',
    priceStd: 100,
    pricePrem: 250,
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&q=80',
    description: 'Taille-crayon métal double',
    badge: null,
  },
]

export const formatPrice = (p) => `${p.toLocaleString('fr-FR')} FCFA`
